#!/usr/bin/env python3
"""
SIH26191 -- Step 9 Output Validation
=====================================
Validates outputs generated by processing/sites/identify_candidate_areas.py.

Checks:
  - Physical file existence
  - CRS correctness (EPSG:32644)
  - Feature count > 0
  - Required attribute fields present
  - Disclaimer field populated
  - No null area_id values
  - Raster nodata and dtype consistency
  - Step 9B base and Step 9C attributed are separate files
  - Step 9B fields preserved in attributed output

USAGE
-----
    python scripts/validate_candidate_areas.py

MANDATORY DISCLAIMER:
All validated outputs remain PRELIMINARY DECISION-SUPPORT CANDIDATES
requiring field verification. Validation confirms data integrity only.
"""

import sys
import io
import json
import pathlib
import datetime

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

_ROOT = pathlib.Path(__file__).resolve().parent.parent
_CONFIG_PATH = _ROOT / "configs" / "project.yaml"

try:
    import yaml
    import numpy as np
    import rasterio
    import geopandas as gpd
except ImportError as exc:
    print(f"[FATAL] Required package missing: {exc}")
    sys.exit(1)

DISCLAIMER_FRAGMENT = "Preliminary decision-support candidate requiring field verification"

REQUIRED_BASE_FIELDS = [
    "area_id", "area_label", "area_m2", "area_hectares",
    "pixel_count", "screening_basis", "disclaimer",
]
REQUIRED_ATTRIBUTED_EXTRA_FIELDS = [
    "mean_slope", "max_slope", "dist_to_nearest_redzone_m",
    "nearest_redzone_id", "nearest_habitation_m",
    "nearest_village_name", "nearest_village_id",
]

PASS = "PASS"
FAIL = "FAIL"
WARN = "WARN"
SKIP = "SKIP"

results = []

def _check(name: str, status: str, detail: str = "") -> None:
    results.append({"name": name, "status": status, "detail": detail})
    icon = {"PASS": "[PASS]", "FAIL": "[FAIL]", "WARN": "[WARN]", "SKIP": "[SKIP]"}.get(status, "[????]")
    print(f"  {icon} {name}" + (f" | {detail}" if detail else ""))

def _section(title: str) -> None:
    print(f"\n{'=' * 68}\n  {title}\n{'=' * 68}")

def main() -> None:
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"\n{'=' * 68}")
    print(f"  SIH26191 -- Step 9 Output Validation")
    print(f"  Generated: {ts}")
    print(f"{'=' * 68}")

    # ------------------------------------------------------------------
    # Load config
    # ------------------------------------------------------------------
    if not _CONFIG_PATH.exists():
        print(f"[FATAL] Config not found: {_CONFIG_PATH}")
        sys.exit(1)
    with open(_CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if "candidate_areas" not in cfg:
        print("[FATAL] 'candidate_areas' section missing from project.yaml")
        sys.exit(1)
    ca_cfg = cfg["candidate_areas"]

    _section("1. FILE EXISTENCE CHECK")

    expected_files = {
        "exclusion_mask_tif":  _ROOT / ca_cfg["outputs"]["exclusion_mask"],
        "area_raster_tif":     _ROOT / ca_cfg["outputs"]["area_raster"],
        "base_gpkg":           _ROOT / ca_cfg["outputs"]["base_gpkg"],
        "base_geojson":        _ROOT / ca_cfg["outputs"]["base_geojson"],
        "attributed_gpkg":     _ROOT / ca_cfg["outputs"]["attributed_gpkg"],
        "attributed_geojson":  _ROOT / ca_cfg["outputs"]["attributed_geojson"],
        "metadata_json":       _ROOT / ca_cfg["outputs"]["metadata_json"],
        "step9_report_md":     _ROOT / "docs" / "step9_candidate_areas_report.md",
    }

    all_exist = True
    for label, path in expected_files.items():
        if path.exists():
            size_kb = path.stat().st_size / 1024
            _check(label, PASS, f"{path.relative_to(_ROOT)} ({size_kb:.1f} KB)")
        else:
            _check(label, FAIL, f"NOT FOUND: {path.relative_to(_ROOT)}")
            all_exist = False

    # Verify 9B and 9C are SEPARATE files
    base_p = _ROOT / ca_cfg["outputs"]["base_gpkg"]
    att_p  = _ROOT / ca_cfg["outputs"]["attributed_gpkg"]
    if base_p != att_p:
        _check("9B_9C_are_separate_files", PASS, "base != attributed (reproducibility preserved)")
    else:
        _check("9B_9C_are_separate_files", FAIL, "SAME PATH -- Step 9B would be overwritten by 9C")

    if not all_exist:
        print("\n[ERROR] Some required output files are missing. Run the pipeline first.")
        print("  python processing/sites/identify_candidate_areas.py")
        sys.exit(2)

    # ------------------------------------------------------------------
    # 2. Raster checks
    # ------------------------------------------------------------------
    _section("2. RASTER INTEGRITY CHECK")

    # Exclusion mask
    excl_path = expected_files["exclusion_mask_tif"]
    try:
        with rasterio.open(str(excl_path)) as src:
            crs_ok = str(src.crs) == "EPSG:32644"
            dtype_ok = src.dtypes[0] == "uint8"
            nodata_ok = src.nodata == 255
            data = src.read(1)
            vals = set(np.unique(data).tolist())
            expected_vals = {0, 1, 255}
            vals_ok = vals.issubset(expected_vals) and len(vals) >= 2
            _check("exclusion_mask.crs", PASS if crs_ok else FAIL, str(src.crs))
            _check("exclusion_mask.dtype", PASS if dtype_ok else FAIL, src.dtypes[0])
            _check("exclusion_mask.nodata", PASS if nodata_ok else WARN, str(src.nodata))
            _check("exclusion_mask.values", PASS if vals_ok else FAIL, f"unique={sorted(vals)}")
            cand_px = int((data == 0).sum())
            excl_px = int((data == 1).sum())
            pixel_area = abs(src.res[0] * src.res[1])
            _check("exclusion_mask.candidate_area",
                   PASS if cand_px > 0 else FAIL,
                   f"{cand_px:,} px = {cand_px * pixel_area / 10000:,.0f} ha")
            _check("exclusion_mask.excluded_area",
                   PASS,
                   f"{excl_px:,} px = {excl_px * pixel_area / 10000:,.0f} ha")
    except Exception as exc:
        _check("exclusion_mask.read", FAIL, str(exc))

    # Area raster
    raster_path = expected_files["area_raster_tif"]
    try:
        with rasterio.open(str(raster_path)) as src:
            crs_ok = str(src.crs) == "EPSG:32644"
            nodata_ok = src.nodata == 0
            data = src.read(1)
            unique_vals = np.unique(data)
            non_zero = unique_vals[unique_vals > 0]
            _check("area_raster.crs", PASS if crs_ok else FAIL, str(src.crs))
            _check("area_raster.nodata", PASS if nodata_ok else WARN, str(src.nodata))
            _check("area_raster.cluster_count",
                   PASS if len(non_zero) > 0 else FAIL,
                   f"{len(non_zero):,} unique cluster IDs")
    except Exception as exc:
        _check("area_raster.read", FAIL, str(exc))

    # ------------------------------------------------------------------
    # 3. Base vector checks
    # ------------------------------------------------------------------
    _section("3. STEP 9B BASE VECTOR CHECK")

    try:
        base_gdf = gpd.read_file(str(expected_files["base_gpkg"]))
        _check("base_gpkg.read", PASS, f"{len(base_gdf):,} features")
        _check("base_gpkg.crs", PASS if str(base_gdf.crs) == "EPSG:32644" else FAIL, str(base_gdf.crs))
        _check("base_gpkg.feature_count", PASS if len(base_gdf) > 0 else FAIL, str(len(base_gdf)))

        # Check required fields
        for field in REQUIRED_BASE_FIELDS:
            present = field in base_gdf.columns
            _check(f"base_gpkg.field.{field}", PASS if present else FAIL,
                   "present" if present else "MISSING")

        # Check area_id uniqueness
        if "area_id" in base_gdf.columns:
            dupes = int(base_gdf["area_id"].duplicated().sum())
            _check("base_gpkg.area_id_unique", PASS if dupes == 0 else FAIL,
                   f"duplicates={dupes}")
            null_ids = int(base_gdf["area_id"].isnull().sum())
            _check("base_gpkg.area_id_no_nulls", PASS if null_ids == 0 else FAIL,
                   f"nulls={null_ids}")

        # Check disclaimer
        if "disclaimer" in base_gdf.columns:
            has_disc = base_gdf["disclaimer"].str.contains(
                DISCLAIMER_FRAGMENT, na=False
            ).all()
            _check("base_gpkg.disclaimer_present", PASS if has_disc else FAIL,
                   "all features have disclaimer" if has_disc else "some missing")

        # Check area values
        if "area_m2" in base_gdf.columns:
            neg_area = int((base_gdf["area_m2"] <= 0).sum())
            _check("base_gpkg.area_positive", PASS if neg_area == 0 else FAIL,
                   f"non-positive areas: {neg_area}")
            total_ha = float(base_gdf["area_hectares"].sum()) if "area_hectares" in base_gdf.columns else 0
            _check("base_gpkg.total_area", PASS, f"{total_ha:,.1f} ha total")

        # Check no forbidden terminology
        forbidden = ["safe site", "approved site", "relocation site", "safe terrain"]
        all_text = " ".join(base_gdf.get("area_label", []).dropna().astype(str).tolist()).lower()
        for term in forbidden:
            if term in all_text:
                _check(f"base_gpkg.terminology.{term.replace(' ', '_')}", FAIL,
                       f"Forbidden term '{term}' found in area_label")
            else:
                _check(f"base_gpkg.terminology.{term.replace(' ', '_')}", PASS,
                       f"Not found (correct)")

        # Check label
        if "area_label" in base_gdf.columns:
            correct_label = "Candidate Topographically Feasible Area"
            has_correct = (base_gdf["area_label"] == correct_label).all()
            _check("base_gpkg.area_label", PASS if has_correct else FAIL,
                   f"'{base_gdf['area_label'].iloc[0]}'" if len(base_gdf) > 0 else "no features")

    except Exception as exc:
        _check("base_gpkg.read", FAIL, str(exc))
        base_gdf = None

    # ------------------------------------------------------------------
    # 4. Attributed vector checks
    # ------------------------------------------------------------------
    _section("4. STEP 9C ATTRIBUTED VECTOR CHECK")

    try:
        att_gdf = gpd.read_file(str(expected_files["attributed_gpkg"]))
        _check("attributed_gpkg.read", PASS, f"{len(att_gdf):,} features")
        _check("attributed_gpkg.crs",
               PASS if str(att_gdf.crs) == "EPSG:32644" else FAIL,
               str(att_gdf.crs))

        # 9B fields preserved
        if base_gdf is not None:
            for field in REQUIRED_BASE_FIELDS:
                preserved = field in att_gdf.columns
                _check(f"attributed_gpkg.9B_field_preserved.{field}",
                       PASS if preserved else FAIL,
                       "preserved" if preserved else "MISSING")

        # Attribution fields
        for field in REQUIRED_ATTRIBUTED_EXTRA_FIELDS:
            present = field in att_gdf.columns
            # Derive actual field name (mean_slope vs mean_slope_degrees)
            # Script uses mean_slope (prefix only)
            _check(f"attributed_gpkg.field.{field}",
                   PASS if present else WARN,
                   "present" if present else "not found (may use different name)")

        # Check mean slope range if present
        slope_col = "mean_slope" if "mean_slope" in att_gdf.columns else None
        if slope_col:
            valid = att_gdf[slope_col].dropna()
            if len(valid) > 0:
                slope_ok = (float(valid.min()) >= 0) and (float(valid.max()) <= 90)
                _check("attributed_gpkg.mean_slope_range", PASS if slope_ok else FAIL,
                       f"[{float(valid.min()):.1f}, {float(valid.max()):.1f}] degrees")

        # nearest_village_pop: check if null or populated
        if "nearest_village_pop" in att_gdf.columns:
            nulls = int(att_gdf["nearest_village_pop"].isnull().sum())
            total = len(att_gdf)
            if nulls == total:
                _check("attributed_gpkg.nearest_village_pop", WARN,
                       "ALL NULL -- demographic attribution unavailable or not applied")
            elif nulls == 0:
                _check("attributed_gpkg.nearest_village_pop", PASS,
                       f"All {total} features have population values")
            else:
                _check("attributed_gpkg.nearest_village_pop", WARN,
                       f"{nulls}/{total} null values")
        else:
            _check("attributed_gpkg.nearest_village_pop", WARN, "column not present")

        # Confirm 9B features count matches
        if base_gdf is not None and len(att_gdf) != len(base_gdf):
            _check("attributed_gpkg.feature_count_matches_base", FAIL,
                   f"attributed={len(att_gdf)}, base={len(base_gdf)} -- MISMATCH")
        elif base_gdf is not None:
            _check("attributed_gpkg.feature_count_matches_base", PASS,
                   f"{len(att_gdf)} features in both")

        # ------------------------------------------------------------------
        # 4b. Explicit LULC Exclusion & Gross/Net Developable Area Check
        # ------------------------------------------------------------------
        _section("4b. LULC PER-CLASS EXCLUSION & GROSS/NET AREA CHECK")

        # Check gross vs net area fields
        if "gross_polygon_area_ha" in att_gdf.columns and "net_developable_area_ha" in att_gdf.columns:
            diff_sum = (att_gdf["gross_polygon_area_ha"] - att_gdf["net_developable_area_ha"]).abs().sum()
            _check("attributed_gpkg.gross_vs_net_developable_area", PASS if diff_sum == 0 else WARN,
                   f"gross_polygon_area_ha == net_developable_area_ha (diff_sum={diff_sum:.2f})")

        # Check dominant_land_cover values
        if "dominant_land_cover" in att_gdf.columns:
            excl_classes_found = att_gdf[att_gdf["dominant_land_cover"].isin([
                "Tree cover", "Built-up", "Snow and ice", "Permanent water bodies", "Herbaceous wetland"
            ])]
            tree_count = int((att_gdf["dominant_land_cover"] == "Tree cover").sum())
            built_count = int((att_gdf["dominant_land_cover"] == "Built-up").sum())
            snow_count = int((att_gdf["dominant_land_cover"] == "Snow and ice").sum())
            water_count = int((att_gdf["dominant_land_cover"] == "Permanent water bodies").sum())

            _check("attributed_gpkg.exclusion.tree_cover", PASS if tree_count == 0 else FAIL,
                   f"0 candidate polygons with Tree Cover (found: {tree_count})")
            _check("attributed_gpkg.exclusion.built_up", PASS if built_count == 0 else FAIL,
                   f"0 candidate polygons with Built-up (found: {built_count})")
            _check("attributed_gpkg.exclusion.snow_ice", PASS if snow_count == 0 else FAIL,
                   f"0 candidate polygons with Snow/Ice (found: {snow_count})")
            _check("attributed_gpkg.exclusion.permanent_water", PASS if water_count == 0 else FAIL,
                   f"0 candidate polygons with Permanent Water (found: {water_count})")
        else:
            _check("attributed_gpkg.dominant_land_cover", WARN, "dominant_land_cover column not found")

    except Exception as exc:
        _check("attributed_gpkg.read", FAIL, str(exc))

    # ------------------------------------------------------------------
    # 5. Metadata JSON check
    # ------------------------------------------------------------------
    _section("5. METADATA JSON CHECK")

    try:
        with open(str(expected_files["metadata_json"]), "r", encoding="utf-8") as f:
            meta = json.load(f)

        _check("metadata.project", PASS if meta.get("project") == "SIH26191" else FAIL,
               meta.get("project", "missing"))
        _check("metadata.crs", PASS if meta.get("crs") == "EPSG:32644" else FAIL,
               meta.get("crs", "missing"))
        _check("metadata.disclaimer_present", PASS if "disclaimer" in meta else FAIL,
               "present" if "disclaimer" in meta else "MISSING")

        applied_params = meta.get("applied_parameters", {})
        for param_name, param_val in applied_params.items():
            _check(f"metadata.param.{param_name}", PASS, str(param_val))

        demog_status = meta.get("habitation_demographics", {}).get("status", "unknown")
        _check("metadata.habitation_demographics_status", PASS, demog_status)

        base_count = meta.get("outputs", {}).get("base_features", "missing")
        base_ha = meta.get("outputs", {}).get("base_total_area_ha", "missing")
        _check("metadata.base_features", PASS if isinstance(base_count, int) and base_count > 0 else FAIL,
               str(base_count))
        _check("metadata.base_total_area_ha", PASS if isinstance(base_ha, (int, float)) else FAIL,
               f"{base_ha} ha" if isinstance(base_ha, (int, float)) else str(base_ha))

    except Exception as exc:
        _check("metadata.read", FAIL, str(exc))

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    _section("VALIDATION SUMMARY")
    passes = sum(1 for r in results if r["status"] == PASS)
    fails  = sum(1 for r in results if r["status"] == FAIL)
    warns  = sum(1 for r in results if r["status"] == WARN)
    skips  = sum(1 for r in results if r["status"] == SKIP)
    total  = len(results)

    print(f"\n  Total checks : {total}")
    print(f"  PASS         : {passes}")
    print(f"  FAIL         : {fails}")
    print(f"  WARN         : {warns}")
    print(f"  SKIP         : {skips}")

    if fails == 0:
        print(f"\n  OVERALL STATUS: PASS")
    else:
        print(f"\n  OVERALL STATUS: FAIL ({fails} failing check(s))")
        print("\n  Failing checks:")
        for r in results:
            if r["status"] == FAIL:
                print(f"    - {r['name']}: {r['detail']}")

    print()
    print("  REMINDER: Outputs are preliminary decision-support candidates requiring")
    print("  field verification. Validation confirms data integrity only.")

    if fails > 0:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
